name       : gnome-logs
version    : '42.0'
release    : 18
source     :
    - https://download.gnome.org/sources/gnome-logs/42/gnome-logs-42.0.tar.xz : 4d5e45169d6bf43902d7a9e9a0793c916eb92daba6ba85b35c8eb6f672cdabd7
homepage   : https://wiki.gnome.org/Apps/Logs
license    : GPL-3.0-or-later
component  : system.utils
summary    : Logs is a viewer for the systemd journal
description: |
    GNOME Logs is a log viewer for the systemd journal.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libhandy-1)
    - desktop-file-utils
    - docbook-xml
    - itstool
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
