name       : gnome-logs
version    : '43.0'
release    : 19
source     :
    - https://download.gnome.org/sources/gnome-logs/43/gnome-logs-43.0.tar.xz : 33a93b975ec27c8487825048aa7b8af7d5c23565abcf7b74c902ab7b3ec20861
homepage   : https://wiki.gnome.org/Apps/Logs
license    : GPL-3.0-or-later
component  : system.utils
summary    : Logs is a viewer for the systemd journal
description: |
    GNOME Logs is a log viewer for the systemd journal.
builddeps  :
    - pkgconfig(gtk4)
    - pkgconfig(libadwaita-1)
    - desktop-file-utils
    - docbook-xml
    - itstool
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
