name       : gnome-logs
version    : 3.20.1
release    : 1
source     :
    - https://download.gnome.org/sources/gnome-logs/3.20/gnome-logs-3.20.1.tar.xz : b797841faac4e176c64497837de27b1b953d16d2482e8a773a48b38117b1367e
license    : GPL-3.0
component  : system.utils
summary    : Logs is a viewer for the systemd journal.
description: |
    Logs is a viewer for the systemd journal.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - desktop-file-utils
    - docbook-xml
    - dogtail
    - itstool
setup      : |
    %configure --enable-tests
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
