name       : gnome-logs
version    : 3.32.1
release    : 12
source     :
    - https://download.gnome.org/sources/gnome-logs/3.32/gnome-logs-3.32.1.tar.xz : c80011fa3d4f8b2e2d9c1ade67095810b72141b58a7bb5a95b5de08397b50342
license    : GPL-3.0-or-later
component  : system.utils
summary    : Logs is a viewer for the systemd journal.
description: |
    Logs is a viewer for the systemd journal.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - desktop-file-utils
    - docbook-xml
    - itstool
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
