name       : gnome-logs
version    : 3.34.0
release    : 14
source     :
    - https://download.gnome.org/sources/gnome-logs/3.34/gnome-logs-3.34.0.tar.xz : 15f4af7085c88321624dc9416f07e7f997fc0fe4c6dd585bce512b11d2e34e9a
license    : GPL-3.0-or-later
component  : system.utils
summary    : Logs is a viewer for the systemd journal.
description: |
    Logs is a viewer for the systemd journal.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - desktop-file-utils
    - docbook-xml
    - itstool
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
