name       : gnome-logs
version    : 3.36.0
release    : 16
source     :
    - https://download.gnome.org/sources/gnome-logs/3.36/gnome-logs-3.36.0.tar.xz : 44766b61a6899e1b4c51ed7a8840608e6b9277f341f856a1e5c08dbd7a733670
license    : GPL-3.0-or-later
component  : system.utils
summary    : Logs is a viewer for the systemd journal.
description: |
    Logs is a viewer for the systemd journal.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - desktop-file-utils
    - docbook-xml
    - itstool
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
