name       : gnome-logs
version    : 3.24.1
release    : 4
source     :
    - http://ftp.acc.umu.se/pub/GNOME/sources/gnome-logs/3.24/gnome-logs-3.24.1.tar.xz : c8d1e5e2cdb0c8f7f9aae9c2b19379b58441f610cc601eb93f60b18ce03833cc
license    : GPL-3.0
component  : system.utils
summary    : Logs is a viewer for the systemd journal.
description: |
    Logs is a viewer for the systemd journal.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - desktop-file-utils
    - docbook-xml
    - dogtail
    - itstool
setup      : |
    %configure --enable-tests
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
