name       : gnome-logs
version    : 3.28.2
release    : 10
source     :
    - https://download.gnome.org/sources/gnome-logs/3.28/gnome-logs-3.28.2.tar.xz : e0ad07b66f77d581cc7e4e76da5d4131f9244fb50559de9315bff59c4be11563
license    : GPL-3.0
component  : system.utils
summary    : Logs is a viewer for the systemd journal.
description: |
    Logs is a viewer for the systemd journal.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - desktop-file-utils
    - docbook-xml
    - dogtail
    - itstool
setup      : |
    %configure --enable-tests
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
