name       : gnome-logs
version    : 3.26.2
release    : 7
source     :
    - https://download.gnome.org/sources/gnome-logs/3.26/gnome-logs-3.26.2.tar.xz : e17ca011e7bea756bd841e027e56cfe8c214bed4817cb35732ace4aa73ff8f5c
license    : GPL-3.0
component  : system.utils
summary    : Logs is a viewer for the systemd journal.
description: |
    Logs is a viewer for the systemd journal.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - desktop-file-utils
    - docbook-xml
    - dogtail
    - itstool
setup      : |
    %configure --enable-tests
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
