name       : gnome-logs
version    : 3.28.5
release    : 11
source     :
    - https://download.gnome.org/sources/gnome-logs/3.28/gnome-logs-3.28.5.tar.xz : 6a881cf0338b0bd0df8afcb6f43755047f72ad3ae5a1932c34644f0643b7867f
license    : GPL-3.0-or-later
component  : system.utils
summary    : Logs is a viewer for the systemd journal.
description: |
    Logs is a viewer for the systemd journal.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - desktop-file-utils
    - docbook-xml
    - dogtail
    - itstool
setup      : |
    %configure --enable-tests
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
