name       : gnome-logs
version    : 3.28.0
release    : 9
source     :
    - https://download.gnome.org/sources/gnome-logs/3.28/gnome-logs-3.28.0.tar.xz : cbe03758b7936a2c54470b5dd13ba6c2d972c23107563949af560b76fe9a7c48
license    : GPL-3.0
component  : system.utils
summary    : Logs is a viewer for the systemd journal.
description: |
    Logs is a viewer for the systemd journal.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - desktop-file-utils
    - docbook-xml
    - dogtail
    - itstool
setup      : |
    %configure --enable-tests
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
