name       : gnome-logs
version    : 3.26.0
release    : 6
source     :
    - https://download.gnome.org/sources/gnome-logs/3.26/gnome-logs-3.26.0.tar.xz : cc870ad5eef16cd4ac14a825277f0298dc2df07f8f757e631e62624aa971880c
license    : GPL-3.0
component  : system.utils
summary    : Logs is a viewer for the systemd journal.
description: |
    Logs is a viewer for the systemd journal.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - desktop-file-utils
    - docbook-xml
    - dogtail
    - itstool
setup      : |
    %configure --enable-tests
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
